name: Add file to remote repo
on: workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repo1        
        uses: actions/checkout@v2
      - run: |
          echo "Hello World" >> Network_Output_payload.txt

      - name: setup git config
        run: |
          # setup the username and email. I tend to use 'GitHub Actions Bot' with no email by default
          git config user.name "monali567"
          git config user.email "monali.mishra1995@gmail.com"

      - name: commit
        run: |
          Token=${{ secrets.Actions_Key }}
          # Stage the file, commit and push
          git add Network_Output_payload.txt
          git commit -m "Add Output file"
          git push APICall main
